### ISSUE TITLE
[bug] AWS responding with InvalidClientException

### ISSUE THREAD

**Issue by pizeyt** [theurichde/go-aws-sso#150] opened 2023-10-21 20:26 UTC
**Describe the bug**

Friday night all was working normally, Saturday morning failing with InvalidClientException

**To Reproduce**
Steps to reproduce the behaviour:
1. using git Bash on Windows
2. winpty go-aws-sso --profile default --region eu-west-1 --persist
3. See error

**Expected behavior**
Get to choose account and role. 

**Error Output**
winpty go-aws-sso --profile default --region eu-west-1 --persist
2023-10-21 21:23:54 ←[34mINFO←[0m AccessToken expired. Start retrieving a new AccessToken
2023-10-21 21:23:54 ←[31mFATAL←[0m Something went wrong: "InvalidClientException: \n{\n  RespMetadata: {\n    StatusCode: 401,\n    RequestID: \"8a512de1-7222-409e-8389-9eeee6ef5dbe\"\n  },\n  Error_: \"invalid_client\",\n  Error_description: \"Invalid client provided\"
\n}"

**Additional context**
Looks like an update on AWS side

**Comment by pizeyt** [comment] 2023-10-21 20:37
This got me restarted: 

 "winpty go-aws-sso config edit" to configure the sso.

Add # to end of  sso url 
set the region to  "eu-west-1" (which it already was. 

I am not clear what changed or why editing the config fixed it.

**Comment by theurichde** [comment] 2023-10-28 15:16
Hey there @pizeyt 

Thanks for opening this issue. I will take a look when I am back from vacation (currently limited access to my machine)

**Comment by theurichde** [comment] 2023-11-08 07:55
I can't reproduce this issue on my side. Works with # and without. I am closing this issue for now. Please feel free to re-open it if something similar pops up again 🍿

**Closed by theurichde** 2023-11-08 07:55 UTC
Labels: bug
