### ISSUE TITLE
[bug] The beep in the account selection menu gets a bit annoying

### ISSUE THREAD

**Issue by XenGi** [theurichde/go-aws-sso#124] opened 2023-06-23 12:02 UTC
**Describe the bug**

When selecting the account from the menu. It beeps every time one presses the arrow keys. This get pretty annoying after a while and could be not so nice in the office.

**To Reproduce**
1. Execute `go-aws-sso`
2. press arrow keys

**Expected behavior**

No audible beep when operating the menu.

**Error Output**

_beep_ :P

**Comment by theurichde** [comment] 2023-06-26 07:42
Hi @XenGi!

Thanks for reporting this issue. As my alert bell is always turned off by default in my terminal, I didn't notice this ever 😅 

This seems to caused by / related to: https://github.com/manifoldco/promptui/issues/49

I will take a look on the code later on 🕵🏼‍♂️

**Comment by theurichde** [comment] 2023-07-04 18:59
Hi @XenGi 👋🏼 

Locally, I can not reproduce the issue for my terminal + shell, so I need your help here. I implemented a suggested fix from promptui and released [v1.3.1-dev.1](https://github.com/theurichde/go-aws-sso/releases/tag/v1.3.1-dev.1)

Would you like to test if the bell is not ringing anymore with this fix?
Thanks!

**Comment by theurichde** [comment] 2023-07-05 14:57
Fixed with #127

**Closed by theurichde** 2023-07-05 14:57 UTC
Labels: bug
